services:
  scraper:
    build: ./scraper
    restart: unless-stopped
    depends_on:
      - rabbitmq
      - mysql
      - redis
    env_file:
      - .env

  rabbitmq:
    image: rabbitmq:3-management-alpine
    restart: unless-stopped
    container_name: ${RABBITMQ_HOST_NAME}
    depends_on:
      - mysql
    ports:
      - ${RABBITMQ_SERVER_PORT0}:5672
      - ${RABBITMQ_SERVER_PORT1}:15672
    volumes:
      - ./rabbitmq/data/:/var/lib/rabbitmq/
      - ./rabbitmq/log/:/var/log/rabbitmq
    env_file:
      - .env

  mysql:
    build:
      context: ./database/
    image: "mysql:8.0"
    container_name: ${MYSQL_HOST_NAME}
    restart: unless-stopped
    ports:
      - ${MYSQL_HOST_PORT}:3306
    volumes:
      - ./database/data:/var/lib/mysql
    env_file:
      - .env

  redis:
    image: redis
    container_name: ${REDIS_HOST_NAME}
    depends_on:
      - rabbitmq
    ports:
      - "6379:6379"
    env_file:
      - .env
